[project]
name = "mediaref"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Suhwan Choi", email = "milkclouds00@gmail.com" }
]
requires-python = ">=3.9"
dependencies = [
    "pydantic>=2.0",  # Requires v2 API (BaseModel, Field)
]

[project.optional-dependencies]
loader = [
    "numpy",
    "opencv-python",
    "pillow",
    "av",
    "requests",
    "loguru",
]
dev = [
    "pytest>=7.0",
    "pytest-cov>=4.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
